config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'top_page#home'
  get '/help', to: 'top_page#help'
  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      confirmations: "users/confirmations"
    }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user, optional: true
  default_scope -> { order(created_at: :desc) }
  # validates :id_user, presence: true
  def self.search(term)
    if term
      where('title LIKE ?', "%#{term}%")
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :jobs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    if user_signed_in?
      @jobs = Job.search(params[:title])
    else
      redirect_to new_user_session_url
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :salary, :skill, :time, :status, :id_user)
    end

    # def jobs_params
    #   params.require(:).permit(:title)
    # end
end

app/controllers/top_page_controller.rb
class TopPageController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :university, :phonenumber, :role])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/top_page_helper.rb
module TopPageHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, class: "hei", placeholder: "Ex: Web application" %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.text_field :salary ,class: "hei", placeholder: "Ex: 2000$" %>
  </div>

  <div class="field">
    <%= form.label :skill %>
    <%= form.text_area :skill, class: "skill", placeholder: "Ex: C#, C, Java" %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time, class: "tb-time", placeholder: "Ex: 3 days or 3 hours" %>
  </div>

  <div class="field">
    <%= form.hidden_field :id_user, value: current_user.id%>
  </div>

  <div class="field">
    <%= form.hidden_field :status, value: '未検閲'%>
  </div>

  <div class="actions bt-createjob">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table border="1" align="center">
  <thead>
    <tr>
      <th >作業タイトル</th>
      <th >給料</th>
      <th >状態</th>
      <th >スキル</th>
      <th >時間</th>
      <th colspan="3">action</th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.salary %></td>
        <td><%= job.status %></td>
        <td><%= job.skill %></td>
        <td><%= job.time %></td>
        <% if user_signed_in? && current_user.role == 2 %>
          <td><%= link_to '表示', job %></td>
          <td><%= link_to '編集', edit_job_path(job) %></td>
          <td><%= link_to '削除', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td><%= link_to '申し込み', '#' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? && current_user.role == 2 %>
  <center><%= link_to '作業登録', new_job_path , class: "to-regi" %></center>
<% end %>

app/views/jobs/new.html.erb
<h1>作業登録</h1>
<div class="form-createjob">
<%= render 'form', job: @job %>

<%# <%= link_to 'Back', jobs_path %>
</div>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%=@job.title %></h3>

<p>
  <strong>Id_user:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @job.salary %>
</p>


<p>
  <strong>Id_user:</strong>
  <%= @job.id_user %>
</p>


<p>
  <strong>Skill:</strong>
  <%= @job.skill %>
</p>

<p>
  <strong>Time:</strong>
  <%= @job.time %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © 2019 チームアオザイ
  </small>
  <nav>
    <ul>
      <li><%= link_to "個人情報の取り扱いについて", '#' %></li>
      <li><%= link_to "このサイトについて", '#' %></li>
      <li><%= link_to "お問い合わせ", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "FINDJOB", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", '#' %></li>
        <li><%= link_to "企業登録", '#' %></li>
        <li><%= link_to "学生登録", '#' %></li>
        <li><%= link_to "ロギングン", '#' %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            アカウント <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "マイページ", '#' %></li>
            
            <li>
              <%= link_to "ログアウト", '#', method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AodaiWeb</title>
    <%= csrf_meta_tags %>
  

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/top_page/help.html.erb
<h1>TopPage#help</h1>
<p>Find me in app/views/top_page/help.html.erb</p>

app/views/top_page/home.html.erb
<div class="textbox">
<%= form_tag(jobs_path, method: :get) do %>
  <%= text_field_tag :title, params[:title],class:"box" %>
  <%= submit_tag '検索',class:"bt-search" %>
<% end %>
<% if user_signed_in? && current_user.role == 2 %>
  <%= link_to '作業登録', new_job_path, class: "btn btn-primary", style: 'color: white' %>
<% end %>
</div>